#mongodb
spring:
  datasource:
    driverClassName: org.h2.Driver
    password:
    url: jdbc:h2:mem:testdb
    username: sa
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
  h2:
    console:
      enabled: true

#logging
logging:
  level:
    root: INFO
server:
  port: ${PORT:8080}

  # H2
  #spring.h2.console.enabled=true
  #spring.h2.console.path=/h2
  # Datasource
  #spring.datasource.url=jdbc:h2:mem:testdb
  #spring.datasource.driverClassName=org.h2.Driver
  #spring.datasource.username=sa
  #spring.datasource.password=
  #spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
  #spring.datasource.continue-on-error=true
  #spring.jpa.hibernate.ddl-auto=create